# -*- coding: utf-8 -*-
"""emea.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7Rsjt6T89vztX3QGZvj7LiZbLmjiB0y

#Set up
"""

!pip install spacy conllu -q

from collections import defaultdict
from conllu import parse

from conllu import parse_incr
from collections import Counter

import matplotlib.pyplot as plt

from spacy.tokens import Doc
from spacy.vocab import Vocab
from spacy import displacy

"""# 2.1 Simple frequency-based sorting

Download the file emea-fr-dev.brown and familiarise yourself with its structure.
The goal:
- sort words by decreasing frequency and display the 100 most
frequent words, together with their number of occurrences.
- Punctuation signs (tagged PONCT) must be ignored, and you should not modify the case of word forms (e.g. le -> Le).

How: You will use a dictionary whose keys are word forms and whose values are occurrence
counts.

Couldn't find the original dev file with POS tag -> Modified To-Do List (for CoNLL-U)

1. Read the file line by line

2. Remove the final newline character

3. Ignore comment lines (lines starting with #)

4. Ignore empty lines (sentence boundaries)

5. Split each remaining line by TAB (\t), not by space

6. Ignore multiword tokens (ID like 3-4)

7. Extract:

- FORM (column 2 → word)

- UPOS (column 4 → POS tag)

8. Add word to dictionary or increment its counter

9. Sort words by decreasing frequency

10. Print top 100 words with counts

## I. Load
"""

!wget https://raw.githubusercontent.com/surfacesyntacticud/SUD_French-Sequoia/refs/heads/main/emea-fr-dev.conllu

with open('/content/emea-fr-dev.conllu', 'r', encoding='utf-8') as f:
    for i, line in enumerate(f):
        if i >= 20:
            break
        print(line.rstrip('\n'))

"""##I. Parse() do everything

The parse() function do everything from 1->8
"""

with open("/content/emea-fr-dev.conllu", "r", encoding="utf-8") as f:
    data = parse(f.read())

count = 0
for sentence in data:
    for token in sentence:
        print(token["form"], token["upos"], token["feats"])
        count += 1
        if count >= 10:
            break
    if count >= 10:
        break

"""Filter based on token['form'] not being None.

Filter out tokens where form is None or UPOS is PUNCT
"""

word_counts = defaultdict(int)

with open("/content/emea-fr-dev.conllu", "r", encoding="utf-8") as f:
    for sentence in parse_incr(f):
        for token in sentence:
            if token["form"] is not None and token["upos"] != "PUNCT":
                word_counts[token["form"]] += 1

"""9. Sort words by decreasing frequency

10. Print top 100 words with counts
"""

# Create a Counter object from the existing word_counts defaultdict.
word_counts_counter = Counter(word_counts)

for word, count in word_counts_counter.most_common(100):
    print(f"{word}\t{count}")

"""##II. Do it by hand"""

#2.1
word_counts = defaultdict(int)
unique_upos_tags = set()

#2.2
word_pos_counts = defaultdict(lambda: defaultdict(int))

with open("/content/emea-fr-dev.conllu", "r", encoding="utf-8") as input_file:
  for line in input_file:
    # 2.1
    # 1 & 2: Line break
    line = line.rstrip("\n")

    # 3 & 4: Ignore empty and comment lines
    if not line or line.startswith("#"):
      continue

    # 5: Split lines into column by TAB
    columns = line.split("\t")

    # check length
    if len(columns) != 10:
      continue

    token_id = columns[0]

    # 6: Ignore multiline word tokens
    if "-" in token_id or "." in token_id: #prev error: if ("-") or ("." in token_id)
      continue

    # 7: extract word and POS
    word = columns[1]      # FORM (keep the case)
    pos = columns[3]       # UPOS
    unique_upos_tags.add(pos)


    # Ignore PUNCT
    if pos == "PUNCT":
      continue

    # 8: Count word frequency
    word_counts[word] += 1

    # 2.2
    word_pos_counts[word][pos] += 1

print("Number of distinct forms: ", len(word_counts))

"""The top 100 words still includes symbols ("/", "%"), numbers, and abbreviation. However, they should not be removed because they are characteristic of the dataset (medicine, newspaper, etc.)."""

# 9: Sort by decreasing frequency
sorted_words = sorted(word_counts.items(), key=lambda x: x[1], reverse=True)

# 10: print top 100
print(f"{"Key":<20}{"Value":<10}")
print(f"{"-"*20:<20}{"-"*10:<10}")

if 'sorted_words' not in locals() or not sorted_words:
    print("Error: sorted_words is not defined or is empty. Please run the previous cells to populate it.")
else:
    for word, count in sorted_words[:100]:
        print(f"{word:<20}{count:<10}")

"""## III. Visualization"""

print(sorted(list(unique_upos_tags)))

# Check if sorted_words exists and has enough data
if 'sorted_words' not in locals() or not sorted_words:
    print("Error: sorted_words is not defined or is empty. Please run the previous cells to populate it.")
else:
    # Limit to the top 30 words
    top_100_words = sorted_words[:30]

    # Define the number of words per chart
    words_per_chart = 10
    # Calculate the number of charts based on the top 100 words
    num_charts = len(top_100_words) // words_per_chart

    for i in range(num_charts):
        start_index = i * words_per_chart
        end_index = start_index + words_per_chart

        # Get the current chunk of words from the top_100_words list
        # These are already sorted from most frequent to least frequent
        current_words_chunk = top_100_words[start_index:end_index]

        # Separate words and counts for plotting
        # Horizontal bars, highest frequency at the top
        # -> reverse the order of words and counts within the chunk for plotting purposes
        words = [item[0] for item in current_words_chunk][::-1]
        counts = [item[1] for item in current_words_chunk][::-1]

        # Create a new figure and axes for each chart
        plt.figure(figsize=(6, 3))
        plt.barh(words, counts, color='pink') # Changed to barh for horizontal bars

        # Add labels and title (swapped for horizontal bars)
        plt.ylabel('Word')
        plt.xlabel('Frequency')
        plt.title(f'Top Distinct Forms ({start_index + 1}-{end_index}) by Frequency')

        # Adjust layout to prevent labels from overlapping
        plt.tight_layout()

        # Display the chart
        plt.show()

"""# 2.2. Computing category ambiguity rates

Compute, on the corpus, the following two measures and compare
them :
- POS-category ambiguity of distinct forms : the average number of possible
POS categories per inflected form (computed on the vocabulary of the corpus).
- POS-category ambiguity of tokens : the average number of possible POS
categories per token (computed on all token occurrences).

This corresponds to the typical distinction between types (distinct forms) and tokens
(form occurrences).

Example (French) :

> la/DET lutte/NC la/CL rebute/V mais/CC elle/CL lutte/V

- What is the POS-category ambiguity of the distinct forms?
- What is the POS-category ambiguity of the form occurrences?

Modify your programme so that it :
- computes both category ambiguity types defined above,
- prints each inflected form sorted by decreasing number of total occurrences,
- displays, for each form, the list of all POS categories it appears with at least once,
together with their respective occurrence counts, sorted by decreasing frequency.

You are allowed to use a dictionary of dictionaries :
- key = inflected form
- value = dictionary mapping POS tags to their counts.

## I. POS-category ambiguity of distinct forms

"inflected form" → count POS tags for separate surface form (parle, parles, parlons)

 "POS-category ambiguity of distinct forms" → how many different POS tags does it appear with?  → For each FORM (columns[1]), Collect all distinct UPOS (columns[3])

Added count POS tag per word into the loop
"""

word_pos_counts["le"] # show tag

"""The type-level ambiguity is defined as:
$A_{\text{type}} = \frac{1}{|V|} \sum_{w \in V} \left| \mathrm{POS}(w) \right|$

- V = set of distinct surface forms

- ∣𝑉∣ = number of distinct forms (vocabulary size)

- POS(w) = set of POS categories observed for form
𝑤

- ∣POS(w)∣ = number of POS categories for that form

Print Sorted by Decreasing POS Frequency
"""

# Compute total frequency per form
word_total_counts = {
    w: sum(pos_counts.values())
    for w, pos_counts in word_pos_counts.items()
}

# Keep only ambiguous forms
ambiguous_words = {
    w: pos_counts
    for w, pos_counts in word_pos_counts.items()
    if len(pos_counts) > 1
}

# Sort ambiguous forms by decreasing total frequency
sorted_ambiguous = sorted(
    ambiguous_words.keys(),
    key=lambda w: word_total_counts[w],
    reverse=True
)

# Print
for word in sorted_ambiguous:
    print(f"\n{word} (total: {word_total_counts[word]})")

    sorted_pos = sorted(
        word_pos_counts[word].items(),
        key=lambda x: x[1],
        reverse=True
    )

    for pos, count in sorted_pos:
        print(f"  {pos}: {count}")

print(len(ambiguous_words))

# Proportion of ambiguous word types
total_types = len(word_pos_counts)
ambiguous_types = len(ambiguous_words)

print(ambiguous_types / total_types)

"""POS-category ambiguity of distinct forms:"""

#Average ambiguity per word type
avg_ambiguity = sum(len(pos_set) for pos_set in word_pos_counts.values()) / total_types
print(avg_ambiguity)

"""## II. POS-category ambiguity of tokens

Tokens = form occurence = word frequency

The token-level ambiguity is defined as
$A_{\text{token}} = \frac{\sum_{w \in V} f(w)\, |\text{POS}(w)|}{\sum_{w \in V} f(w)}$.


Where
- 𝑉 = set of distinct surface forms (vocabulary)
- 𝑓(𝑤) = frequency of word form 𝑤
- POS(𝑤) = set of POS categories observed for
𝑤
- ∣POS(𝑤)∣ = number of POS categories for 𝑤
"""

total_tokens = sum(word_counts.values())

weighted_sum = 0

for word in word_counts:
    ambiguity = len(word_pos_counts[word])
    freq = word_counts[word]
    weighted_sum += ambiguity * freq

token_ambiguity = weighted_sum / total_tokens

print(token_ambiguity)

"""# 3.1 Reading a dependency tree

The file sequoia.conll contains 3,099
sentences from L’Est Républicain, EMEA, French Wikipedia, and Europarl, annotated
with morphological and syntactic information, more precisely dependency trees.

A dependency is represented as a triple (governor word, dependency label, dependent
word).

To familiarise yourself with this representation :
- draw the dependency tree for the second sentence in the file;
- identify the particularity of the root of this tree.

Write a programme that reads these dependency trees. Note that the CoNLL format
is not inherently suited to recursive reading. You may choose between :
- a non-recursive structure using a Node class and a Tree class that stores nodes,
governor and dependent relations;
- a recursive structure where each Tree instance contains node information and a
list of dependent subtrees.

In both cases, aim for a single pass over the sequence of words. Since one does not
know in advance where a sentence ends, you must handle a partially built tree structure.
Moreover, a governor may appear earlier than the line describing it, so you must manage
partially filled node instances and maintain a list of node instances for all positions in
the sentence, including in the recursive version.

what are:
 - dependent word: big
 - dependency label: adj
 - governor word (head)

possible solution:
- node (the word) and tree (its relations)
  - head, head-adj-Tom
- tree: node (the word) and dependent subtree (list of relation)
  - tree: head, toe-is-blue the-sucks

## I. Load and Overview
"""

!wget --no-check-certificate https://www.linguist.univ-paris-diderot.fr/~mcandito/divers/sequoia.7.0.expanded.conll

with open('/content/sequoia.7.0.expanded.conll', 'r', encoding='utf-8') as file2:
    for i, line in enumerate(file2):
        if i >= 50:
            break
        print(line.rstrip('\n'))

# Read file
with open("/content/sequoia.7.0.expanded.conll", "r", encoding="utf-8") as f:
    data = f.read()

sentences = parse(data) # Added this line to parse the data

num_sentences = len(sentences)

# Compute sentence lengths once
sentence_lengths = [
    len([tok for tok in s if isinstance(tok["id"], int)])
    for s in sentences
]

print("Sentences:", num_sentences)
print("Tokens:", sum(sentence_lengths))
print(f"Minimum sentence length:", min(sentence_lengths))
print(f"Maximum sentence length:", max(sentence_lengths))
print("Average sentence length:", sum(sentence_lengths) / num_sentences)

# Extract lengths and counts
length_counts = Counter(sentence_lengths)
sentence_length_distribution = sorted(length_counts.items())

lengths = [item[0] for item in sentence_length_distribution]
counts = [item[1] for item in sentence_length_distribution]

# Create the bar chart
plt.figure(figsize=(15, 7))
plt.bar(lengths, counts, color='blue')

# Add labels and title
plt.xlabel('Sentence Length')
plt.ylabel('Frequency')
plt.title('Distribution of Sentence Lengths')
plt.xticks(rotation=90)
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Display the plot
plt.show()

"""## II. Draw dependency tree for second sentence"""

sentences = parse(data)
sentence = sentences[1]  # second sentence

words = [token["form"] for token in sentence]
heads = [token["head"] - 1 for token in sentence]  # spaCy is 0-indexed
deps = [token["deprel"] for token in sentence]

vocab = Vocab()
doc = Doc(vocab, words=words)

for i, token in enumerate(doc):
    token.dep_ = deps[i]
    token.head = doc[heads[i]] if heads[i] >= 0 else token

displacy.render(doc, style="dep", jupyter=True)

"""The root word:
- One root per sentence
- It is the only node without a governor (head = 0)
- link to all other words (directly and indirectly)

## III. Read dependency tree
-> non-recursive structure using a Node class and a Tree class that stores node

- single pass
- maintain a list of node instances for all positions in the sentence
"""

# Node Class
class Node:
    def __init__(self, idx, form):
        self.id = idx
        self.form = form
        self.head = None      #govenor
        self.deprel = None    #dependency label
        self.children = []    #dependency word

# Tree Class
class Tree:
    def __init__(self):
        self.nodes = {}
        self.root = None

    def add_token(self, idx, form, head, deprel):
        # Create node if not exists
        if idx not in self.nodes:
            self.nodes[idx] = Node(idx, form)
        else:
            self.nodes[idx].form = form

        node = self.nodes[idx]
        node.deprel = deprel

        # Handle root
        if head == 0:
            self.root = node
        else:
            # Create placeholder head if needed
            if head not in self.nodes:
                self.nodes[head] = Node(head, None)

            node.head = self.nodes[head]
            self.nodes[head].children.append(node)

# Single pass reading
def read_conll(file_path):
    trees = []
    current_tree = Tree()

    with open(file_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()

            # Sentence boundary
            if not line:
                trees.append(current_tree)
                current_tree = Tree()
                continue

            if line.startswith("#"):
                continue

            parts = line.split("\t")
            idx = int(parts[0])
            form = parts[1]
            head = int(parts[6])
            deprel = parts[7]

            current_tree.add_token(idx, form, head, deprel)

    return trees

"""# 3.2 Estimation using relative frequency

**Probability estimation**

Consider verbs that have (at least one) nominal subject. Using the provided corpus, estimate by relative frequency :
- p=P(INV) : the probability that the subject is inverted (i.e. post-verbal),
- P(REL) : the probability that such a verb is the head of a relative clause,
- P(REL|INV) and P(INV | REL) : compute this in two ways — directly by restric
ting the fundamental set, and via Bayes’ theorem.

**Likelihood**

 Express the likelihood of the parameter p = P(INV), given the observations
(verb occurrences and the position of their subject). What property does the estimator
obtained in the previous section have? Provide a precise and developed explanation.
"""